##' General 3-type linear multitype birth-death-sampling process (BDMM, Stadler psi/r parameterization)
##'
##' A linear multitype birth-death-sampling process on 3 demes (type1..type3),
##' following the continuous reaction set of Vaughan & Stadler (2025, MBE).
##' Per capita, a type i individual: gives birth to a type j offspring at rate
##' lambda_i_j (parent stays type i); migrates i->j at rate m_i_j; is removed
##' unobserved at rate mu_i; and is sampled at overall rate psi_i, being removed
##' on sampling with probability r_i (SampR, sample_death) or retained with
##' probability 1-r_i (SampNR, sampled ancestor). Present-time (rho) sampling and
##' skyline time-variation are NOT included. Generated by gen_bdmm.R -- do not
##' hand-edit; regenerate.
##'
##' @name mtbd3
##' @family Genealogy processes
##' @aliases MTBD3
##' @include getinfo.R
##' @param lambda_1_1 birth rate type1 parent -> type1 child
##' @param lambda_1_2 birth rate type1 parent -> type2 child
##' @param lambda_1_3 birth rate type1 parent -> type3 child
##' @param lambda_2_1 birth rate type2 parent -> type1 child
##' @param lambda_2_2 birth rate type2 parent -> type2 child
##' @param lambda_2_3 birth rate type2 parent -> type3 child
##' @param lambda_3_1 birth rate type3 parent -> type1 child
##' @param lambda_3_2 birth rate type3 parent -> type2 child
##' @param lambda_3_3 birth rate type3 parent -> type3 child
##' @param m_1_2 migration type1 -> type2
##' @param m_1_3 migration type1 -> type3
##' @param m_2_1 migration type2 -> type1
##' @param m_2_3 migration type2 -> type3
##' @param m_3_1 migration type3 -> type1
##' @param m_3_2 migration type3 -> type2
##' @param mu_1 unobserved removal rate in type1
##' @param mu_2 unobserved removal rate in type2
##' @param mu_3 unobserved removal rate in type3
##' @param psi_1 overall sampling rate for type1
##' @param psi_2 overall sampling rate for type2
##' @param psi_3 overall sampling rate for type3
##' @param r_1 probability a sampled type1 individual is removed
##' @param r_2 probability a sampled type2 individual is removed
##' @param r_3 probability a sampled type3 individual is removed
##' @param I1_0 initial lineages in type1
##' @param I2_0 initial lineages in type2
##' @param I3_0 initial lineages in type3
##' @param object a previously computed simulation
##' @param time end timepoint of simulation
##' @param t0 beginning timepoint of simulation
##' @return \code{runMTBD3} and \code{continueMTBD3} return objects of class \sQuote{gpsim} with \sQuote{model} attribute \dQuote{MTBD3}.
##'
NULL

##' @rdname mtbd3
##' @export
runMTBD3 <- function (
  time, t0 = 0,
  lambda_1_1 = 1, lambda_1_2 = 0.1, lambda_1_3 = 0.1, lambda_2_1 = 0.1, lambda_2_2 = 1, lambda_2_3 = 0.1, lambda_3_1 = 0.1, lambda_3_2 = 0.1, lambda_3_3 = 1, m_1_2 = 0, m_1_3 = 0, m_2_1 = 0, m_2_3 = 0, m_3_1 = 0, m_3_2 = 0, mu_1 = 0.5, mu_2 = 0.5, mu_3 = 0.5, psi_1 = 0.1, psi_2 = 0.1, psi_3 = 0.1, r_1 = 1, r_2 = 1, r_3 = 1, I1_0 = 1, I2_0 = 0, I3_0 = 0
) {
  params <- c(lambda_1_1=lambda_1_1,lambda_1_2=lambda_1_2,lambda_1_3=lambda_1_3,lambda_2_1=lambda_2_1,lambda_2_2=lambda_2_2,lambda_2_3=lambda_2_3,lambda_3_1=lambda_3_1,lambda_3_2=lambda_3_2,lambda_3_3=lambda_3_3,m_1_2=m_1_2,m_1_3=m_1_3,m_2_1=m_2_1,m_2_3=m_2_3,m_3_1=m_3_1,m_3_2=m_3_2,mu_1=mu_1,mu_2=mu_2,mu_3=mu_3,psi_1=psi_1,psi_2=psi_2,psi_3=psi_3,r_1=r_1,r_2=r_2,r_3=r_3)
  ivps <- c(I1_0=I1_0,I2_0=I2_0,I3_0=I3_0)
  x <- .Call(P_makeMTBD3,params,ivps,t0)
  .Call(P_runMTBD3,x,time) |>
    structure(model="MTBD3",class=c("gpsim","gpgen"))
}

##' @rdname mtbd3
##' @export
continueMTBD3 <- function (
  object, time,
  lambda_1_1 = NA, lambda_1_2 = NA, lambda_1_3 = NA, lambda_2_1 = NA, lambda_2_2 = NA, lambda_2_3 = NA, lambda_3_1 = NA, lambda_3_2 = NA, lambda_3_3 = NA, m_1_2 = NA, m_1_3 = NA, m_2_1 = NA, m_2_3 = NA, m_3_1 = NA, m_3_2 = NA, mu_1 = NA, mu_2 = NA, mu_3 = NA, psi_1 = NA, psi_2 = NA, psi_3 = NA, r_1 = NA, r_2 = NA, r_3 = NA
) {
  params <- c(
    lambda_1_1=lambda_1_1,lambda_1_2=lambda_1_2,lambda_1_3=lambda_1_3,lambda_2_1=lambda_2_1,lambda_2_2=lambda_2_2,lambda_2_3=lambda_2_3,lambda_3_1=lambda_3_1,lambda_3_2=lambda_3_2,lambda_3_3=lambda_3_3,m_1_2=m_1_2,m_1_3=m_1_3,m_2_1=m_2_1,m_2_3=m_2_3,m_3_1=m_3_1,m_3_2=m_3_2,mu_1=mu_1,mu_2=mu_2,mu_3=mu_3,psi_1=psi_1,psi_2=psi_2,psi_3=psi_3,r_1=r_1,r_2=r_2,r_3=r_3
  )
  x <- .Call(P_reviveMTBD3,object,params)
  .Call(P_runMTBD3,x,time) |>
    structure(model="MTBD3",class=c("gpsim","gpgen"))
}
