#!/usr/bin/env Rscript
## gen_bdmm.R -- emit a phylopomp YAML spec for the general n-type linear
## multitype birth-death-sampling model (BDMM), continuous-reaction form, in
## Stadler's native (psi, r) parameterization.
##
## Target: Vaughan & Stadler (2025, MBE 42(6)) continuous reactions. Present-time
## (rho) sampling and skyline time-variation are NOT emitted -- they need engine
## extensions and cannot be expressed as `rate:` events.
##
## Reactions (per-capita in the source-deme count I_i):
##   Birth_ij      lambda_i_j * I_i        I_j += 1 ; birth(type_i,type_j)   (all i,j)
##   Migration_ij  m_i_j     * I_i         I_i -= 1 ; I_j += 1 ; migrate(i,j) (i != j)
##   Death_i       mu_i      * I_i         I_i -= 1 ; death(type_i)
##   SampR_i       r_i * psi_i * I_i       I_i -= 1 ; sample_death(type_i)
##   SampNR_i      (1-r_i) * psi_i * I_i   sample(type_i)
##
## Usage:
##   Rscript gen_bdmm.R 4                 > yaml/bdmm4.yml
##   Rscript gen_bdmm.R 3 --name BDMM3 --out yaml/bdmm3.yml
##   Rscript gen_bdmm.R 5 --psi 0.2 --r 0.5 --out yaml/bdmm5.yml
##
## Or source() it and call generate_bdmm(n, ...) directly.

## format a numeric default: doubles always carry a decimal point; ints don't
.fmtnum <- function(x, typ) {
  if (identical(typ, "int")) return(as.character(as.integer(round(x))))
  s <- format(x, trim = TRUE, scientific = FALSE)
  if (!grepl("\\.", s)) s <- paste0(s, ".0")
  s
}

.flow <- function(name, desc, default, typ = "double") {
  sprintf("  %s: {name: %s, description: %s, type: %s, default: %s}",
          name, name, desc, typ, .fmtnum(default, typ))
}

generate_bdmm <- function(n, name = NULL,
                          diag_lambda = 1.0, offdiag_lambda = 0.1,
                          m = 0.0, mu = 0.5, psi = 0.1, r = 1.0) {
  if (n < 1) stop("n must be >= 1")
  if (is.null(name)) name <- sprintf("BDMM%d", n)
  ii <- seq_len(n)
  L <- character(0)
  add <- function(...) L[[length(L) + 1L]] <<- paste0(...)

  add("name: ", name)
  add(sprintf("description: General %d-type linear multitype birth-death-sampling process (BDMM, Stadler psi/r parameterization)", n))
  add("details: |-")
  add(sprintf("  A linear multitype birth-death-sampling process on %d demes (type1..type%d),", n, n))
  add("  following the continuous reaction set of Vaughan & Stadler (2025, MBE).")
  add("  Per capita, a type i individual: gives birth to a type j offspring at rate")
  add("  lambda_i_j (parent stays type i); migrates i->j at rate m_i_j; is removed")
  add("  unobserved at rate mu_i; and is sampled at overall rate psi_i, being removed")
  add("  on sampling with probability r_i (SampR, sample_death) or retained with")
  add("  probability 1-r_i (SampNR, sampled ancestor). Present-time (rho) sampling and")
  add("  skyline time-variation are NOT included. Generated by gen_bdmm.R -- do not")
  add("  hand-edit; regenerate.")

  add("demes:")
  for (i in ii) add(sprintf("  - type%d", i))

  add("parameter:")
  for (i in ii) for (j in ii) {
    d <- if (i == j) diag_lambda else offdiag_lambda
    add(.flow(sprintf("lambda_%d_%d", i, j),
              sprintf("birth rate type%d parent -> type%d child", i, j), d))
  }
  for (i in ii) for (j in ii) if (i != j) {
    add(.flow(sprintf("m_%d_%d", i, j),
              sprintf("migration type%d -> type%d", i, j), m))
  }
  for (i in ii) add(.flow(sprintf("mu_%d", i),
                          sprintf("unobserved removal rate in type%d", i), mu))
  for (i in ii) add(.flow(sprintf("psi_%d", i),
                          sprintf("overall sampling rate for type%d", i), psi))
  for (i in ii) add(.flow(sprintf("r_%d", i),
                          sprintf("probability a sampled type%d individual is removed", i), r))

  add("ivp:")
  for (i in ii) {
    d <- if (i == 1) 1 else 0
    add(.flow(sprintf("I%d_0", i),
              sprintf("initial lineages in type%d", i), d, typ = "int"))
  }

  add("state:")
  for (i in ii) add(sprintf("  I%d: {name: I%d, type: int}", i, i))

  add("rinit: |-")
  for (i in ii) add(sprintf("  state.I%d = params.I%d_0;", i, i))
  for (i in ii) add(sprintf("  graft(type%d,params.I%d_0);", i, i))

  add("events:")
  for (i in ii) for (j in ii) {
    add(sprintf("  birth_%d_%d:", i, j))
    add(sprintf("    rate: params.lambda_%d_%d * state.I%d", i, j, i))
    add(sprintf("    jump: state.I%d += 1; birth(type%d,type%d);", j, i, j))
  }
  for (i in ii) for (j in ii) if (i != j) {
    add(sprintf("  mig_%d_%d:", i, j))
    add(sprintf("    rate: params.m_%d_%d * state.I%d", i, j, i))
    add(sprintf("    jump: state.I%d -= 1; state.I%d += 1; migrate(type%d,type%d);", i, j, i, j))
  }
  for (i in ii) {
    add(sprintf("  death_%d:", i))
    add(sprintf("    rate: params.mu_%d * state.I%d", i, i))
    add(sprintf("    jump: state.I%d -= 1; death(type%d);", i, i))
  }
  ## SampR_i: sampled AND removed, rate r_i * psi_i * I_i
  for (i in ii) {
    add(sprintf("  sampdeath_%d:", i))
    add(sprintf("    rate: params.r_%d * params.psi_%d * state.I%d", i, i, i))
    add(sprintf("    jump: state.I%d -= 1; sample_death(type%d);", i, i))
  }
  ## SampNR_i: sampled WITHOUT removal, rate (1 - r_i) * psi_i * I_i
  for (i in ii) {
    add(sprintf("  samp_%d:", i))
    add(sprintf("    rate: (1 - params.r_%d) * params.psi_%d * state.I%d", i, i, i))
    add(sprintf("    jump: sample(type%d);", i))
  }

  paste0(paste(L, collapse = "\n"), "\n")
}

## ---- CLI ----------------------------------------------------------------
if (sys.nframe() == 0L) {
  args <- commandArgs(trailingOnly = TRUE)
  if (length(args) < 1L)
    stop("usage: Rscript gen_bdmm.R <n> [--name NAME] [--out FILE] [--m x] [--mu x] [--psi x] [--r x] [--diag-lambda x] [--offdiag-lambda x]")
  getflag <- function(flag, default = NULL) {
    k <- which(args == flag)
    if (length(k) == 0L) return(default)
    args[k + 1L]
  }
  n    <- as.integer(args[1L])
  name <- getflag("--name")
  out  <- getflag("--out")
  num  <- function(flag, d) { v <- getflag(flag); if (is.null(v)) d else as.numeric(v) }
  txt <- generate_bdmm(
    n, name = name,
    diag_lambda    = num("--diag-lambda", 1.0),
    offdiag_lambda = num("--offdiag-lambda", 0.1),
    m   = num("--m", 0.0),
    mu  = num("--mu", 0.5),
    psi = num("--psi", 0.1),
    r   = num("--r", 1.0)
  )
  if (is.null(out)) {
    cat(txt)
  } else {
    cat(txt, file = out)
    message(sprintf("wrote %s  (%d events, %d demes)", out, 2 * n * n + 2 * n, n))
  }
}
